import { drizzle } from 'drizzle-orm/mysql2';
import mysql from 'mysql2/promise';

// Production Database Configuration - Auto-generated by install.js
const connectionConfig = {
  host: '5.181.218.15',
  port: 3306,
  user: 'netiedb',
  password: 'h5pLF9833',
  database: 'ienetdb',
  charset: 'utf8mb4',
};

// Connection Pool
export const pool = mysql.createPool({
  ...connectionConfig,
  waitForConnections: true,
  connectionLimit: 10,
  queueLimit: 0,
});

export const db = drizzle(pool, { mode: 'default' });

// Health Check
export async function healthCheck() {
  try {
    const connection = await pool.getConnection();
    const [rows] = await connection.execute('SELECT 1 as test');
    connection.release();
    return { status: 'healthy', database: 'ienetdb' };
  } catch (error) {
    return { status: 'unhealthy', error: (error as Error).message };
  }
}

// Connection Test
export async function testConnection() {
  const health = await healthCheck();
  if (health.status === 'healthy') {
    console.log('✅ Database connection successful');
    return true;
  } else {
    console.error('❌ Database connection failed:', health.error);
    return false;
  }
}
